services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3SitemapLocator\:
    resource: '../Classes/*'
    exclude:
      - '../Domain/Exception/*'
      - '../Domain/Model/*'

  EliasHaeussler\Typo3SitemapLocator\Cache\SitemapsCache:
    arguments:
      $cache: '@cache.sitemap_locator'

  EliasHaeussler\Typo3SitemapLocator\EventListener\SiteConfigurationListener:
    tags:
      - name: event.listener
        identifier: 'sitemapLocatorSiteConfigurationListener'

  EliasHaeussler\Typo3SitemapLocator\Sitemap\SitemapLocator:
    arguments:
      $providers: !tagged_iterator { tag: 'sitemap_locator.sitemap_provider', default_priority_method: 'getPriority' }

  cache.sitemap_locator:
    class: 'TYPO3\CMS\Core\Cache\Frontend\PhpFrontend'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      - !php/const EliasHaeussler\Typo3SitemapLocator\Extension::KEY
